name : testing 

on: 
  push:

env:
  list: 'dev , master'
  
jobs:
  git:
    runs-on: linux-latest
    steps:
      - name: print if branch correct
        if: contains(${{env.list}}, github.ref)
        run: echo ${{github.ref}}
  
