name: testing

on:
  push:

env:
  list: '[dev,master]'

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: print if branch correct
        if: contains(env.list, github.ref_name)
        run: echo ${{ github.ref }}
