name: Docker Image CI

on:
  push:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - run:  echo ${{runner.os}}
    - uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
