name: Docker Image CI

on:
  push:
  workflow_dispatch:
jobs:
 build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      - run: |
            pwd
            ls -al
      - name: Upload Docker image artifact
        run: |
          docker save your-registry.azurecr.io/${{ github.repository }}:${{ github.sha }} | gzip > image.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: image.tar.gz
 scan-docker:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Download Docker image artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image

      - name: Call Trivy Scan Workflow
        uses: ./.github/workflows/trivy-scan.yml
        with:
          docker_image: your-registry.azurecr.io/${{ github.repository }}:${{ github.sha }}

          
